name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses:
      devopsb78/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-frontend
#      npm_install: false
#    secrets: inherit